---
development:
  cloud_name: dffv87sla
  api_key: '485425772948891'
  api_secret: N9GV7JQpOfx0pGS9bCnq_N8ky_Q
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dffv87sla
  api_key: '485425772948891'
  api_secret: N9GV7JQpOfx0pGS9bCnq_N8ky_Q
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dffv87sla
  api_key: '485425772948891'
  api_secret: N9GV7JQpOfx0pGS9bCnq_N8ky_Q
  enhance_image_tag: true
  static_image_support: false
